config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :items

  root 'items#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader

  enum style: [ :style1, :style2, :style3 ]

  validates :name, :style, :price, :photo, :description,  presence: true

  filterrific(
    default_filter_params: { sort_desc: true },
    available_filters: [
      :sort_desc,
      :name_contains,
      :with_style,
      :price_min,
      :price_max
    ]
  )

  scope :sort_desc, -> (flag) {
    method = flag ? :desc : :asc
    order(created_at: method)
  }
  scope :name_contains, -> (name) { where("name LIKE ?", "%#{name}%") }
  scope :with_style, -> (style) { where(style: Item.styles[style]) }
  scope :price_min, -> (price) { where("price >= ?", price) }
  scope :price_max, -> (price) { where("price <= ?", price) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @filterrific = initialize_filterrific(
       Item,
       params[:filterrific]
     ) or return
     
    @items = @filterrific.find

   respond_to do |format|
     format.html
     format.js
   end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :style, :price, :photo, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="form-group">
    <%= f.label :style %><br>
    <%= f.select :style, Item.styles.map { |key, value| [key.humanize, key] }, {}, class: "form-control", placeholder: "Choose Style" %>
  </div>

  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control", placeholder: "Price", :step => 0.1 %>
  </div>
  <div class="form-group">
    <%= f.label :photo %><br>
    <%= f.file_field :photo, class: "form-control"%>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to 'Back', items_path, class: "btn btn-default", role: "button" %>
  </div>
<% end %>

app/views/items/_list.html.erb
<% if @items.blank? %>
  <div class="panel panel-default">
    <div class="panel-body">
      "No Items Available"
    </div>
  </div>
<% end %>

<div class="row" id="filterrific_results">
  <% @items.each do |item| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= image_tag(item.photo.thumb.url) %>
        <div class="caption">
          <h3>
            <%= link_to item.name, item %>
          </h3>
          <p><b>style:</b><%= item.style%> </p>
          <p><b>price:</b><%= item.price%> </p>

          <% if admin_signed_in? %>
            <p>
              <%= link_to 'Edit', edit_item_path(item), class:"btn btn-default", role: "button" %>
              <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items
  <% if admin_signed_in? %>
      <%= link_to 'New Item', new_item_path, class: "btn btn-primary pull-right", role: "button" %>
  <% end %>
</h1>

<%= form_for_filterrific @filterrific, html: { class: "form-inline" } do |f| %>
  <div class="form-group">
    Name
    <%= f.text_field(:name_contains, class: 'form-control filterrific-periodically-observed') %>
  </div>
  <div class="form-group">
    Style
    <%= f.select(:with_style, Item.styles.map { |key, value| [key.humanize, key] },
     { include_blank: '- Any -' }, class: "form-control filterrific-periodically-observed") %>
  </div>
  <div class="form-group">
    Price Min
    <%= f.number_field(:price_min, class: "form-control filterrific-periodically-observed", step: 0.5) %>
  </div>
  <div class="form-group">
    Price Max
    <%= f.text_field(:price_max,  class: "form-control filterrific-periodically-observed", step: 0.5) %>
  </div>
<% end %>

<br/>

<%= render(
  partial: 'items/list',
  locals: { items: @items }
) %>

app/views/items/index.js.erb
<% js = escape_javascript(
  render(partial: 'items/list', locals: { items: @items })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @item.name %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @item.photo.medium.url, class:"img-rounded" %>
      </div>
      <div class="col-md-4">
        <p><strong>Name:</strong><%= @item.name %> </p>
        <p><strong>Description:</strong><%= @item.description %> </p>
        <p><strong>Style:</strong><%= @item.style %> </p>
        <p><strong>Price:</strong><%= @item.price %> </p>

        <% if admin_signed_in? %>
          <p>
            <%= link_to 'Edit', edit_item_path(@item), class:"btn btn-primary", role: "button" %>
            <%= link_to 'Back', items_path, class:"btn btn-default" %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bicycle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if admin_signed_in? %>
    <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
  <% end %>

<%= yield %>

</body>
</html>